# frozen_string_literal: true

# Model for storing content generated by the AI Writer plugin.
class AiWriterContent < ActiveRecord::Base
  belongs_to :issue
  belongs_to :author, class_name: 'User'

  validates :issue, presence: true
  validates :author, presence: true
  validates :generated_content, presence: true
end 
