# frozen_string_literal: true

# Model for storing content generated by the AI Writer plugin.
class AiWriterContent < ActiveRecord::Base
  belongs_to :issue
  belongs_to :author, class_name: 'User'

  validates :issue, presence: true
  validates :author, presence: true
  validates :generated_content, presence: true

  # Status enum
  enum status: { draft: 0, applied: 1 }

  # Scope for finding applied contents
  scope :applied, -> { where(status: :applied) }

  # Default status
  after_initialize :set_default_status, if: :new_record?

  private

  def set_default_status
    self.status ||= :draft
  end
end 
